name: portfolio
description: Meu Portfólio Flutter Web
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/
